## Introduction To SciKit-Learn 

1.scikit-learn Work Flow

work-flow
1.getting data ready
2.choose. the right algorithm for our problems
3.Fit the model/algorithm and use it to make predictions on our data
4.Evaluating a model
5.Improve a model
6.save and load a trained model
7. putting it all together
 

In [135]:
#Get Data Ready
import numpy as np
import pandas as pd
heart_disease = pd.read_csv("../datasets/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [136]:
#Create x - Features Matrix
x = heart_disease.drop("target", axis=1)

#Create y  (labels):
y = heart_disease["target"]

In [137]:
#2. Choose the right Model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100) 

clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [138]:
#3 fit the model to the training data

from sklearn.model_selection import train_test_split   
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2)


In [139]:
clf.fit(x_train , y_train);

In [140]:
x_train.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
265   66    1   0       112   212    0        0      132      1      0.1   
36    54    0   2       135   304    1        1      170      0      0.0   
281   52    1   0       128   204    1        1      156      1      1.0   
41    48    1   1       130   245    0        0      180      0      0.2   
39    65    0   2       160   360    0        0      151      0      0.8   

     slope  ca  thal  
265      2   1     2  
36       2   0     2  
281      1   0     0  
41       1   0     2  
39       2   0     2

In [141]:
y_train.head()

265    0
36     1
281    0
41     1
39     1
Name: target, dtype: int64

In [142]:
#Make a Prediction
y_preds = clf.predict(x_test)

In [143]:
y_preds

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [144]:
# 4. Evaluate the Model 
#Accuracy for Training Data
clf.score(x_train , y_train)  

1.0

In [145]:
#Test Data
clf.score(x_test , y_test)

0.7868852459016393

In [146]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.72      0.81      0.76        26
           1       0.84      0.77      0.81        35

    accuracy                           0.79        61
   macro avg       0.78      0.79      0.78        61
weighted avg       0.79      0.79      0.79        61



In [147]:
confusion_matrix(y_test, y_preds)

array([[21,  5],
       [ 8, 27]])

In [148]:
accuracy_score(y_test, y_preds)

0.7868852459016393

In [149]:
# 5. Improve the Model 
#Try different amount n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying Model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train, y_train)
    print(f"Model Accuracy on test set: {clf.score(x_test, y_test)*100:.2f}%")
    print(" ")

Trying Model with 10 estimators...


Model Accuracy on test set: 80.33%
 
Trying Model with 20 estimators...
Model Accuracy on test set: 83.61%
 
Trying Model with 30 estimators...
Model Accuracy on test set: 83.61%
 
Trying Model with 40 estimators...
Model Accuracy on test set: 77.05%
 
Trying Model with 50 estimators...
Model Accuracy on test set: 80.33%
 
Trying Model with 60 estimators...
Model Accuracy on test set: 80.33%
 
Trying Model with 70 estimators...
Model Accuracy on test set: 80.33%
 
Trying Model with 80 estimators...
Model Accuracy on test set: 78.69%
 
Trying Model with 90 estimators...
Model Accuracy on test set: 78.69%
 


In [150]:
# We found highest accuracy at estimators = 80  
# We Update our model with the new estimator
clf = RandomForestClassifier(n_estimators=80)
clf.fit(x_train , y_train);
clf.score(x_test, y_test)

0.8032786885245902

In [151]:
# 6. Save the Model and Load it
import pickle 

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [152]:
# Import Loaded Model
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"));
loaded_model.score(x_test, y_test)

0.8032786885245902

## 1. Getting our Data Ready to be used 
Three main things we have to do:
    1.Split the data into features and labels (usually `x` and `y`)
    2.Filling (also called imputing ) or disregarding missing values
    3.Converting non numerical values to numerical values (also called Feature Coding)
    

In [153]:
#1.1 Make sure all data is numerical
car_sales = pd.read_csv("../datasets/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [154]:
len(car_sales) # returns number of rows of data

1000

In [155]:
#step 1: split the data to x and y 
X = car_sales.drop("Price", axis=1)
Y= car_sales["Price"]

#split into training set
X_train , X_test , Y_train , Y_test = train_test_split(X, Y , test_size=0.2)


In [156]:
#We need to convert all the values to numeric values
#Turn the catergories into numbers
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] 
#Doors is numeric but it can be classified into different categories like 4 doors , 3 doors , 5 doors
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X



array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [157]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [158]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4     False        True        False        False         False   
1        5      True       False        False        False         False   
2        4     False        True        False        False         False   
3        4     False       False        False         True         False   
4        3     False       False         True        False         False   
..     ...       ...         ...          ...          ...           ...   
995      4     False       False        False         True          True   
996      3     False       False         True        False         False   
997      4     False       False         True        False         False   
998      4     False        True        False        False         False   
999      4     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 10 columns]

In [159]:
np.random.seed(42)
X_train , X_test , Y_train , Y_test  =train_test_split(transformed_X, Y, test_size = 0.2) #New X


In [160]:
#Build Model
from sklearn.ensemble import RandomForestRegressor #It can predict number
model = RandomForestRegressor(n_estimators=80)
model.fit(X_train, Y_train)
model.score(X_test, Y_test)


0.3093435017735806

1.2 Dealing with Missing Values 
    1.Fill the missing values (imputation)
    2. Remove the missing data altogether
    

In [161]:
car_sales_missing = pd.read_csv("../datasets/car-sales-extended-missing-data.csv")
car_sales_missing.head(10)

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [162]:
car_sales_missing.tail(10)

Make Colour  Odometer (KM)  Doors    Price
990  Toyota  White       173408.0    4.0   8082.0
991   Honda   Blue       235985.0    4.0   9184.0
992   Honda  Green        54721.0    4.0  27419.0
993  Nissan  Black       162523.0    4.0   4696.0
994     BMW   Blue       163322.0    3.0  31666.0
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

In [163]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [164]:
#Split to x and y
x  = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]



In [165]:
#Lets convert the values to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)], 
                                  remainder="passthrough")
transformed_X = transformer.fit_transform(x)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

### option1. Fill Missing Data with Pandas


In [166]:
#Fill the missing Columns
car_sales_missing.fillna({"Make":"missing",
                          "Colour":"missing",
                          "Odometer (KM)":"missing",
                          "Doors":4,
                          }, inplace=True)



In [167]:
car_sales_missing.isna().sum() #We can observe that there are no more NaN values in Make , Colour and Doors Columns

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [168]:
#To remove Missing values from Price Column we will drop the rows with missing Values
car_sales_missing.dropna(subset=["Price"], inplace=True)

In [169]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [170]:
#Now we have filled or removed all the missing values

In [171]:
car_sales_missing #We can see that NaN values are replaced by missing or 4(Doors Column)

Make Colour Odometer (KM)  Doors    Price
0      Honda  White       35431.0    4.0  15323.0
1        BMW   Blue      192714.0    5.0  19943.0
2      Honda  White       84714.0    4.0  28343.0
3     Toyota  White      154365.0    4.0  13434.0
4     Nissan   Blue      181577.0    3.0  14043.0
..       ...    ...           ...    ...      ...
995   Toyota  Black       35820.0    4.0  32042.0
996  missing  White      155144.0    3.0   5716.0
997   Nissan   Blue       66604.0    4.0  31570.0
998    Honda  White      215883.0    4.0   4001.0
999   Toyota   Blue      248360.0    4.0  12732.0

[950 rows x 5 columns]

In [172]:
x = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [173]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)], 
                                  remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

## Option 2 Fill the Missing Data with sklearn

In [174]:
car_sales_missing = pd.read_csv("../datasets/car-sales-extended-missing-data.csv")
car_sales_missing.head(10)

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [175]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [176]:
#Drop Rows with Missing Values in Price Column
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [177]:
#Split into x and y
X  =  car_sales_missing.drop("Price", axis =1)
Y = car_sales_missing["Price"]

In [178]:
#Fill missing values using sklearn
from sklearn.impute import SimpleImputer
from sklearn.compose  import ColumnTransformer

#Fill categorical values with missing and numerical values with mean

cat_imputer = SimpleImputer(strategy="constant",fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#Define Column_features
cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

#Define Imputer (Something that fills missing data)
imputer = ColumnTransformer([("cat_imputer", cat_imputer,cat_features),
                            ("door_imputer", door_imputer, door_features),
                             ("num_imputer", num_imputer, num_features)
                             ])
#Transfrom the data
filled_X = imputer.fit_transform(X)
filled_X
pd.DataFrame(filled_X)
#We can Observe that all the missing values are filled based on the conditions


0      1    2         3
0      Honda  White  4.0   35431.0
1        BMW   Blue  5.0  192714.0
2      Honda  White  4.0   84714.0
3     Toyota  White  4.0  154365.0
4     Nissan   Blue  3.0  181577.0
..       ...    ...  ...       ...
945   Toyota  Black  4.0   35820.0
946  missing  White  3.0  155144.0
947   Nissan   Blue  4.0   66604.0
948    Honda  White  4.0  215883.0
949   Toyota   Blue  4.0  248360.0

[950 rows x 4 columns]

In [179]:
pd.DataFrame(filled_X).isna().sum() #No Missing values

0    0
1    0
2    0
3    0
dtype: int64

In [180]:
car_sales_filled = pd.DataFrame(filled_X, columns =["Make", "Colour", "Odometer (KM)","Doors"])
car_sales_filled

Make Colour Odometer (KM)     Doors
0      Honda  White           4.0   35431.0
1        BMW   Blue           5.0  192714.0
2      Honda  White           4.0   84714.0
3     Toyota  White           4.0  154365.0
4     Nissan   Blue           3.0  181577.0
..       ...    ...           ...       ...
945   Toyota  Black           4.0   35820.0
946  missing  White           3.0  155144.0
947   Nissan   Blue           4.0   66604.0
948    Honda  White           4.0  215883.0
949   Toyota   Blue           4.0  248360.0

[950 rows x 4 columns]

In [181]:
car_sales_filled.head(20)

Make Colour Odometer (KM)          Doors
0     Honda  White           4.0        35431.0
1       BMW   Blue           5.0       192714.0
2     Honda  White           4.0        84714.0
3    Toyota  White           4.0       154365.0
4    Nissan   Blue           3.0       181577.0
5     Honda    Red           4.0        42652.0
6    Toyota   Blue           4.0       163453.0
7     Honda  White           4.0  130987.447894
8   missing  White           4.0       130538.0
9     Honda   Blue           4.0        51029.0
10   Nissan  White           4.0       167421.0
11   Nissan  Green           4.0        17119.0
12   Nissan  White           4.0       102303.0
13  missing  White           4.0       134181.0
14    Honda   Blue           4.0       199833.0
15   Toyota   Blue           4.0       205592.0
16   Toyota    Red           4.0        96742.0
17      BMW  White           5.0       194189.0
18   Nissan  White           3.0        67991.0
19   Nissan   Blue           4.0       215820.0

In [182]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
dtype: int64

In [183]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)], 
                                  remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x913 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [184]:
#Now we have got our data as numbers and filled 
#Lets fit a model
np.random.seed(9)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test , Y_train , Y_test = train_test_split(transformed_X, Y, test_size=(0.2))

model = RandomForestRegressor(n_estimators=80)
model.fit(X_train , Y_train)
model.score(X_test, Y_test)


0.042836844493988946

In [185]:
len(car_sales_filled) , len(car_sales) #Low Accuracy is due to less data 

(950, 1000)

## 2. Choosing the right Estimator/Algorithm 
Sklearn uses estimator as another term for machine Learning model or algorithm
    
    1.Classification - Predicting whether a sample is one thing or another
    2.Regression - Predicting a Number

use sklearn ml map to find the right estimator 

### 2.1 Picking Machine Learning Model for a Regression Problem

In [186]:
#Loading california_housing dataset for regressing 
from sklearn.datasets import fetch_california_housing

california = fetch_california_housing()
california;


In [187]:
california_df = pd.DataFrame(california["data"] , columns=california["feature_names"])
california_df["target"] = pd.Series(california["target"])
california_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [188]:
len(california_df)

20640

In [189]:
# Working with  ridge regression Model
#Ref sklearn machine learning map to find the right model...
from sklearn.linear_model import Ridge

#setup random seed
np.random.seed(42)

#Create the data (split the data into x and y)
X = california_df.drop("target",axis=1)
Y = california_df["target"]

#Split to train and test set

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size=0.2)

#Initiate the Model

model = Ridge()
model.fit(X_train , Y_train)
model.score(X_test, Y_test)

0.5758549611440127

In [190]:
# How to improve the model
#Using Ensemble method RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

#Setup Seed so that data can be reproduced
np.random.seed(42)
#Create the data
X= california_df.drop("target", axis=1)
Y = california_df["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X, Y , test_size=0.2)

model_rf = RandomForestRegressor(n_estimators=80)
model_rf.fit(X_train , Y_train)
model_rf.score(X_test, Y_test)



0.8062702737063999

In [191]:
model.score(X_test, Y_test) #We can clearly see that RandomForestRegressor model is 
#performing better than Ridge hence we should got with RandomForestRegressor model in this case

0.5758549611440127

In [192]:
## 2.2 Choosing an estimator for classification problem
#Go to the map


In [193]:
heart_disease = pd.read_csv("../datasets/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [194]:
#For classification Problems
#SkLearn ML map suggest to use LinearSVC  model

from sklearn.svm import LinearSVC
#setup randomseed to reproduce the data
np.random.seed(42)

#Setup Data X and Y
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

#split the data
X_train, X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.2)

#Initiate  LinearSVC
clf = LinearSVC()
clf.fit(X_train , Y_train)

clf.score(X_test, Y_test)



0.8688524590163934

In [195]:

heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [196]:
#InCase the Model had not worked:
#We will try another model
#For classification we can also use RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

clf2 = RandomForestClassifier(n_estimators=80)
clf2.fit(X_train, Y_train)
clf2.score(X_test, Y_test)

0.8524590163934426

## 3.Fit the Model/Algorithm on our Data use it to make Predictions
3.1 - <--Fit the Data-->

<-Differrent Names->
##
    X = Features , Feature_Variable , Data
    Y = Labels , Targets , Target_variables

In [197]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

X= heart_disease.drop("target" ,axis=1)
Y = heart_disease["target"]

X_train , X_test , Y_train ,Y_test = train_test_split(X,Y, test_size=0.2)

clf = RandomForestClassifier(n_estimators=80)

#<---Fit the Data--->
clf.fit(X_train , Y_train) #Finds patterns in data and Trains the ML model
clf.score(X_test , Y_test) 



0.8524590163934426

# 3.2 Make Predictions Using Machine Learning Models

 Use a Trained Model to make Predictions

#There are 2 ways:

1.predict()

2.predict_proba()


In [198]:
print(X_test.shape)
y_preds = clf.predict(X_test) 
np.mean(y_preds==Y_test)

(61, 13)


np.float64(0.8524590163934426)

In [199]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test  , y_preds) 

0.8524590163934426

Make Predictions using `predict_proba()`


In [200]:
clf.predict_proba(X_test[:5]) #returns probabilities of a classification label
#Here the value at index[i][1] is greater when true and smaller when false

array([[0.9   , 0.1   ],
       [0.475 , 0.525 ],
       [0.425 , 0.575 ],
       [0.8375, 0.1625],
       [0.1625, 0.8375]])

In [201]:
california_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [202]:
# predict() can also be used for regression models
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = california_df.drop("target", axis=1)
Y = california_df["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X, Y , test_size=0.2)

model = RandomForestRegressor()

model.fit(X_train, Y_train)
model.score(X_test, Y_test)


#Make Predictions
y_preds= model.predict(X_test)

In [203]:
y_preds

array([0.49384  , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67901  ])

In [204]:
np.array(Y_test) #We can see that the values are almost equal.

array([0.477  , 0.458  , 5.00001, ..., 5.00001, 0.723  , 1.515  ])

In [205]:
#Compare the predictions to the truth

from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, y_preds)

np.float64(0.32659871732073664)

## 4.Evaluating Model

    Three Ways to Evaluated sklearn models
    1. Estimator score method
    2. The scoring parameter
    3. Problem-specific metric functions
    

In [206]:
#!.Using Score Method 

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size=0.2)

clf = RandomForestClassifier()

clf.fit(X_train , Y_train)
clf.score(X_test, Y_test) #Score Method returns mean accuracy of the data or labels

0.8524590163934426

In [207]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = california_df.drop("target", axis=1)
Y = california_df["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X, Y , test_size=0.2)

model = RandomForestRegressor()

model.fit(X_train, Y_train);

In [208]:
model.score(X_test, Y_test) #In Regression Models the score Return the coefficient of determination of the prediction.


0.8065734772187598

In [209]:
#2.Evaluating model using scoring parameter
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train , Y_train)
clf.score(X_test, Y_test)


0.8524590163934426

In [210]:
#Using Cross Val Score

cross_val_score(clf, X, Y) #Returns the score for 5 different sets of data

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

In [211]:
#Lets compare the results of score and cross_val_score
np.random.seed(42)
score_val = clf.score(X_test, Y_test)

cross_val_score_res  = np.mean(cross_val_score(clf, X,Y));

#Comparison

score_val , cross_val_score_res



(0.8524590163934426, np.float64(0.8248087431693989))

In [212]:
#scoring parameter is set to none by default

cross_val_score(clf, X , Y , scoring=None)


array([0.78688525, 0.86885246, 0.80327869, 0.78333333, 0.76666667])

## 4.2.1 classification of model evaluation metrics

    1.Accuracy

    2.Area under ROC curve

    3.Confusion Matrix
    
    4.Classification report
    

In [214]:
#1.Accuracy
from sklearn.model_selection import cross_val_score

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size=0.2)

accuracy = np.mean(cross_val_score(clf , X, Y , scoring=None))
print(f"Heart Disease Model Accuracy Using cross_val_score is :{accuracy*100:.2f}%")

Heart Disease Model Accuracy Using cross_val_score is :82.15%
